container:
  image: node:latest

test_task:
  name: Tests
  node_modules_cache:
    folder: node_modules
    ingerprint_script: cat package-lock.json
    populate_script: npm ci
  test_script: npm run lint && npm test


deploy_task:
  only_if: $CIRRUS_BRANCH == 'master'
  depends_on: Tests
  node_modules_cache:
    folder: node_modules
    ingerprint_script: cat package-lock.json
    populate_script: npm ci
  env:
    GITHUB_TOKEN: ENCRYPTED[95468f36d823780edd5f0d64b335bf2c6bd0366d9a4c464a427595ce669c00a5b2c41ca004db36342ad0101da00a1103]
    USER: korneef
    REPO: test-ci-cd
  deploy_script: 
    - git config --global user.name "Cirrus-CI"
    - git config --global user.email "ci@cirruslabs.org"
    - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
    - git remote set-url origin https://x-access-token:$GITHUB_TOKEN:@github.com/$USER/$REPO
    - npm run build && npx push-dir --dir=dist --branch=gh-pages --force --verbose
